# Define a job to be invoked later in a workflow.
# Do not change the name of the jobs!

jobs:
  build-and-test:
    steps:
      # Either a syntax OR a build command is required
      build:
        # Compiles source code files
        command:

      syntax:
        # Performs static syntax check on source code files
        command:  python -m compileall

      requirements:
        # Must have: command to install requirements.txt
        command: pip install -r

      run:
        # Must have: command to run tests
        command: python -m pytest